[Metadata]
Name=Fcitx5 Theme Template
Version=1.0
Author=justTOBBI, Isabelinc, Kurome, Luke Hogan
Description=Use this template to create new theme
ScaleWithDPI=True

# #f6dcac: Text and icons
# #05182e: Background and selected text
# #faa968: Highlights and border

[InputPanel]
Font=Sans 13
Spacing=3
NormalColor=#f6dcac
HighlightCandidateColor=#05182e
HighlightColor=#faa968

[InputPanel/TextMargin]
Left=18
Right=18
Top=8
Bottom=8

[InputPanel/Background]
Image=panel.png

[InputPanel/Background/Margin]
Left=10
Right=10
Top=10
Bottom=10

[InputPanel/Highlight]
Color=#faa968

[InputPanel/Highlight/Margin]
Left=18
Right=18
Top=8
Bottom=8

[Menu]
Font=Sans 10
NormalColor=#f6dcac
Spacing=3

[Menu/Background]
Image=panel.png

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#faa968

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
Color=#05182e

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
