[ids]
04d9:0169

include common.conf

[main]
capslock = leftcontrol
scrolllock = capslock
insert = f13
leftalt = f14
rightalt = f17
rightmeta = rightalt
leftcontrol = f24
rightcontrol = katakanahiragana
