[ids]
04d9:0169

include common.conf

[main]
capslock = leftcontrol
scrolllock = f13
pause = katakanahiragana
leftalt = f14
rightalt = f17
rightmeta = rightalt
leftcontrol = f24
rightcontrol = capslock