[ids]
04d9:0169

include common.conf

[main]
capslock = layer(control)
scrolllock = f13
pause = katakanahiragana
leftalt = f14
rightmeta = f17
leftcontrol = f24
# compose is the menu key
rightcontrol = compose
