[ids]
05ac:0274

include common.conf

[main]
capslock = layer(control)
scale = katakanahiragana
dashboard = f13
leftalt = layer(meta)
leftmeta = f14
rightmeta = f17
leftcontrol = f24

[shift]
tab = sysrq
