[ids]
05ac:0274:f2d1f5c2

include common.conf

[main]
capslock = layer(control)
scale = katakanahiragana
dashboard = f13
leftalt = layer(meta)
rightalt = f17
leftmeta = f14
rightmeta = layer(alt)
leftcontrol = f24

[shift]
tab = sysrq
