# Copy / Paste
bindd = $CMD, C, Universal copy, sendshortcut, , XF86Copy, activewindow
bindd = $CMD, V, Universal paste, sendshortcut, , XF86Paste, activewindow
bindd = $CMD, X, Universal cut, sendshortcut, , XF86Cut, activewindow
bindd = $CMD CTRL, V, Clipboard manager, exec, omarchy-launch-walker -m clipboard
